"""Insertanto nueva modelo Contextfile a la base de datos para permitir guardar paths de archivos que se pueden utilizar para el contexto del LLM

Revision ID: 13ecf988e2ae
Revises: 758bb8a00885
Create Date: 2026-01-19 20:25:26.095335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ecf988e2ae'
down_revision: Union[str, Sequence[str], None] = '758bb8a00885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
