"""Insertando nueva columna para aceptar IDfiles en Conversations

Revision ID: 758bb8a00885
Revises: a6cb7ea21743
Create Date: 2026-01-17 22:43:22.184233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758bb8a00885'
down_revision: Union[str, Sequence[str], None] = 'a6cb7ea21743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('context', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'context')
    # ### end Alembic commands ###
