"""Corrigiendo relacion de tabla email_verification

Revision ID: a6cb7ea21743
Revises: 452d6812bc7b
Create Date: 2026-01-14 22:31:38.309010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6cb7ea21743'
down_revision: Union[str, Sequence[str], None] = '452d6812bc7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
